"""Changed create_date field

Revision ID: 47ab1320ee9a
Revises: 7238416eb346
Create Date: 2024-02-04 17:28:00.922565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ab1320ee9a'
down_revision = '7238416eb346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
