"""Changed fields create_date  models CharityProjects and Donation

Revision ID: 860989d969f0
Revises: 47ab1320ee9a
Create Date: 2024-02-04 18:18:24.798195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860989d969f0'
down_revision = '47ab1320ee9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
